#!/bin/sh

# Linux From Scratch "RyzenOS 11.2" Fetch for @PKGNAM@

# Copyright @YEAR@ @AUTHOR@
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# Read PKGNAM from User Input
echo "Please enter the package you wish to build"
read PKGNAM

case "$PKGNAM" in 
    xfce4-dev-tools*) $PKGNAM=xfce4-dev-tools ;;
esac

mkdir -pv /tmp/pkgget
cd /tmp/pkgget
wget https://raw.githubusercontent.com/RyznOS/repo/main/RyzenOS/11.2/PKGS/$PKGNAM/$PKGNAM.SlackBuild
wget https://raw.githubusercontent.com/RyznOS/repo/main/RyzenOS/11.2/PKGS/$PKGNAM/slack-desc 
echo "Building $PKGNAM Using the RyzenOS 11.2 Build System"
chown root:root $PKGNAM.SlackBuild
chmod +x $PKGNAM.SlackBuild
exec /tmp/pkgget/$PKGNAM.SlackBuild


